language: node_js
node_js:
  - 12.9.1
cache: npm

install:
  - npm ci

script: 
  - npm test

deploy:
  provider: page
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: develop